
services:
  my_postgres_db:
    image: postgres:16
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: briefbdd
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
